### ISSUE TITLE
cudaCheckError failed

### ISSUE THREAD

**Issue by lolongcovas** [longcw/faster_rcnn_pytorch#6]
Hi I have a cuda card K40, I compiled the pytorch and this repository correctly. I ran train.py and I got this error:

cudaCheckError() failed : invalid device function

any idea?

**Comment by longcw** [comment]
See this https://github.com/smallcorgi/Faster-RCNN_TF/issues/19

> I got the same error (i.e., cudaCheckError() failed : invalid device function) with my Tesla K40. When I changed the -arch parameter in lib/make.sh to sm_35, and rerun make.sh, it worked.

```
# Which CUDA capabilities do we want to pre-build for?
# https://developer.nvidia.com/cuda-gpus
#   Compute/shader model   Cards
#   6.1		      P4, P40, Titan X so CUDA_MODEL = 61
#   6.0                    P100 so CUDA_MODEL = 60
#   5.2                    M40
#   3.7                    K80
#   3.5                    K40, K20
#   3.0                    K10, Grid K520 (AWS G2)
#   Other Nvidia shader models should work, but they will require extra startup
#   time as the code is pre-optimized for them.
CUDA_MODELS=30 35 37 52 60 61
```

**Comment by fangyan93** [comment]
@longcw  Hello, I am using AWS EC2 GPU to run demo.py, getting 'cudaCheckError() failed : invalid device function'.
 Since GPU used is GRID K520 on my instance, I follow your post to change -arch parameter in steup.py and make.sh to sm_30 and rerun make.sh, but this error is still there when I run './tools/demo.py --model ./VGG.....ckpt'. Could you please give me some help?
